.. raw:: html

  <h2>Description</h2>

Please describe the field ``app_proto_tc``.

..
  .. raw:: html

  <h2>Related configuration items</h2>

  .. code-block:: yaml

  # enable/disable the blah feature.
  blah: true
  
  The above configuration snippet is valid for Suricata versions 3.2 - 4.1.4.

..
  .. raw:: html

   <h2>Related fields</h2>

  - foo
  - bar

..
  .. raw:: html

   <h2>Known Problems</h2>

  - foo
  - bar

..
  .. raw:: html

   <h2>Example</h2>

  .. code-block:: json
  :emphasize-lines: 2

   {
       "timestamp": "2016-05-27T21:51:40.565045+0000",
       "event_type": "foobar",
       "flow_id": 1918431989874897
   }
  

..
  .. raw:: html

  <h2>External references</h2>

  - https://github.com/corelight/community-id-spec